/**
 * TimelineFactory.js: A simplified factory to structure journey segments.
 * Now injects Station Headers before each segment and processes transfer details.
 */
export class TimelineFactory {

    static createOriginNodes(station, selectedExit, finalRoute) {
        const nodes = [];
        const rawItems = finalRoute?.rawItems || [];
        nodes.push({
            isStationHeader: true,
            stationNameKo: station.name_ko || station.title,
            stationNameEn: station.name_en,
            lineName: rawItems[0]?.lineNm || station.line,
            type: 'ORIGIN'
        });

        if (finalRoute?.originDetailedPath) {
            nodes.push(...finalRoute.originDetailedPath);
        }
        return nodes;
    }

    static createTransitNodes(transitData, originNodes, activeRoute) {
        const nodes = [];

        if (activeRoute?.rawItems && activeRoute.rawItems.length > 0) {
            // Process detailed transfer items generated by RouteService
            activeRoute.rawItems.forEach(item => {
                if (item.transitDetailedPath && item.transitDetailedPath.length > 0) {
                    nodes.push({
                        isStationHeader: true,
                        stationNameKo: item.stnNm,
                        stationNameEn: item.stnNm, // English name might not be available in KRIC data, fallback to raw
                        lineName: item.lineNm,
                        type: 'TRANSFER'
                    });
                    nodes.push(...item.transitDetailedPath);
                }
            });
        }

        // Fallback or secondary transit data block (if needed for backward compatibility or extra info)
        if (nodes.length === 0) {
            nodes.push({ type: 'transit', ...transitData });
        }

        return nodes;
    }

    static createDestinationNodes(station, selectedExit, activeRoute) {
        const nodes = [];
        const rawItems = activeRoute?.rawItems || [];
        nodes.push({
            isStationHeader: true,
            stationNameKo: station.name_ko || station.title,
            stationNameEn: station.name_en,
            lineName: rawItems[rawItems.length - 1]?.lineNm || station.line,
            type: 'DESTINATION'
        });

        if (activeRoute?.destinationDetailedPath) {
            nodes.push(...activeRoute.destinationDetailedPath);
        }
        return nodes;
    }
}

